### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by acosmicflamingo** [Nikoloutsos/explicitDependencyImportCheck#5]
It appears that this plugin requires the machine to have Apple Silicon hardware; I'm getting this kind of error when trying to use it:
```
Error Domain=NSPOSIXErrorDomain Code=86 "Bad CPU type in executable"
```

**Comment by Nikoloutsos** [comment]
Hey @acosmicflamingo, thanks for reporting.
Looks like the xcframework that I've built does include only `["x86_64-apple-macosx", "arm64-apple-macosx"]` hence the error message you're receiving. But I think we can expand it to support more.

To reproduce the problem, are you running on a Macbook with intel or something else?

**Comment by acosmicflamingo** [comment]
@Nikoloutsos thanks for the reply! I am running it on a Macbook with Intel hardware. To be specific, 2.4 GHz 8-Core Intel Core i9.

**Comment by Nikoloutsos** [comment]
Indeed @acosmicflamingo, the x86_64 architecture for intel was initially missing. I managed to find some free time today and have now added support for it. Everything should be working fine now. When you have a chance, please test it by adding the following to your Package.swift so that we can make a new release:

```swift
dependencies: [
    .package(url: "https://github.com/Nikoloutsos/explicitDependencyImportCheck", branch: "feature/include_x86_64_architecture_in_sitrep_binary")
],
```

**Comment by acosmicflamingo** [comment]
Works like a charm! Thanks!!! 🤩
